replicaCount: 1
nfs:
  server: 10.111.249.11
  path: /data/retain
  reclaimPolicy: Retain
storageClass:
  create: true
  provisionerName: tuanvm-nfs-storage-retain-provisioner
  defaultClass: true
  name: nfs-subdir-retain
  allowVolumeExpansion: true
  reclaimPolicy: Retain
  archiveOnDelete: true
  accessModes: ReadWriteOnce
  volumeBindingMode: Immediate
