apiVersion: v1
kind: Pod
metadata:
  name: localjs
spec:
  containers:
    - name: localjs
      image: 080196/hello-kube
      ports:
      - containerPort: 3000
      resources:
        requests:
          memory: "64Mi"
          cpu: "1"
        limits:
          memory: "512Mi"
          cpu: "1"
        
