kind: ConfigMap
apiVersion: v1
metadata:
  name: example-configmap
  namespace: default
data: # not spec
  # Configuration Values are stored as key-value pairs
  title: "introduction to k8s"
  auth: "tuanvm"
  publish_date: "28/12/2025"