apiVersion: v1
kind: Pod
metadata:
  name: localpy
spec:
  containers:
    - name: localpy
      image: configmap-example:v0.2
      imagePullPolicy: Never
      envFrom:
        - configMapRef:
            name: example-configmap
      volumeMounts:
      - name: cfm-volume
        mountPath: "/app/config"
        readOnly: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "1"
        limits:
          memory: "512Mi"
          cpu: "1"
  volumes:
    - name: cfm-volume
      configMap:
        name: cm-from-dir
        items:
        - key: "conf-example-1.conf"
          path: "conf-example-1.conf"
        - key: "conf-example-2.conf"
          path: "conf-example-2.conf"
