apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
    apptype: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort:  80
      name:  http
    resources:
      requests:
        memory: "64Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
