apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - name: socket-server
        image: jmalloc/echo-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: "3001"
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          tcpSocket:
            port: 3001

