apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: busybox
    resources:
      requests:
        memory: "1Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep", "9999999"]
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: CPU_REQUEST_MILLICORES
        valueFrom:
          resourceFieldRef:
            resource: requests.cpu
            divisor: 1m
      - name: MEM_REQUEST_MB
        valueFrom:
          resourceFieldRef:
            resource: requests.memory
            divisor: 1Mi
